repos:
  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests
        entry: python -m unittest discover -s tests
        language: system
        pass_filenames: false

      - id: pylint
        name: Run pylint
        entry: pylint src/mt/univariate.py
        language: system
        pass_filenames: false